name: metaltrade
description: A new Flutter project.
 
 
publish_to: 'none'  

version: 1.0.1+2

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.3.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  go_router: ^10.0.0
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.5
  cached_network_image: ^3.2.3
  hive: ^2.2.3
  flutter_secure_storage: ^8.0.0
  flutter_dotenv: ^5.0.2
  intl: ^0.18.0
  path_provider: ^2.0.15
  marquee: ^2.2.3
  webview_flutter: ^4.2.2
  page_view_dot_indicator: ^2.1.0
  pinput: ^2.2.31
  web_socket_channel: ^2.4.0
  stomp_dart_client: ^0.4.4
  dotted_border: ^2.0.0+3
  image_picker: ^1.0.1
  file_picker: ^5.3.3
  fluttertoast: ^8.2.2
  easy_localization: ^3.0.2
  otp_autofill: ^3.0.0
  flutter_web_frame: ^1.0.0
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: fonts/PlayfairDisplay-Regular.ttf
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        
  assets:
    - dotenv
    - assets/
    - assets/welcome/
    - assets/login/
    - assets/home/
    - assets/dashboard/
    - assets/translations/

    
flutter_assets:
  assets_path: assets/
  output_path: lib/core/constants/
  filename: assets.dart

   
   
   
   

   
   

   
   

   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
