// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_DBABIafevZMPPzQslp9XEo7UviweLCU',
    appId: '1:389282404678:web:6338ace854a5f30e58ad47',
    messagingSenderId: '389282404678',
    projectId: 'metaltradingplatform',
    authDomain: 'metaltradingplatform.firebaseapp.com',
    storageBucket: 'metaltradingplatform.appspot.com',
    measurementId: 'G-1MJJ80KLPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_zbc2WMJPLyEd8CTMXm1zhjowBZJ7v20',
    appId: '1:389282404678:android:09a19ef1098f066558ad47',
    messagingSenderId: '389282404678',
    projectId: 'metaltradingplatform',
    storageBucket: 'metaltradingplatform.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD68WPQIvse0V8nH1ecQ7oAm5PgcGDLwAw',
    appId: '1:389282404678:ios:58ca7702b34ca37458ad47',
    messagingSenderId: '389282404678',
    projectId: 'metaltradingplatform',
    storageBucket: 'metaltradingplatform.appspot.com',
    iosClientId: '389282404678-hsd3umsjc098qib0tmm36vsgv4kccfn8.apps.googleusercontent.com',
    iosBundleId: 'com.app.metaltrade',
  );
}
